<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StickyNotes\Controller\IndexController' => __DIR__ . '/src/StickyNotes/Controller/IndexController.php',
    'StickyNotes\Model\StickyNotesTable'     => __DIR__ . '/src/StickyNotes/Model/StickyNotesTable.php',
    'StickyNotes\Model\Entity\StickyNote'    => __DIR__ . '/src/StickyNotes/Model/Entity/StickyNote.php',
    'StickyNotes\Module'                     => __DIR__ . '/Module.php',
);
