<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TesteQRCode\Controller\IndexController' => __DIR__ . '/src/TesteQRCode/Controller/IndexController.php',
    'TesteQRCode\Module'                     => __DIR__ . '/Module.php',
);
