<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TesteTwig\Controller\IndexController' => __DIR__ . '/src/TesteTwig/Controller/IndexController.php',
    'TesteTwig\Module'                     => __DIR__ . '/Module.php',
);
