<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Service\ExemploService'     => __DIR__ . '/src/Application/Service/ExemploService.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Helper\LeftLinks'           => __DIR__ . '/src/Application/Helper/LeftLinks.php',
    'Application\Module'                     => __DIR__ . '/Module.php',
);
