<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Controller\IndexController'    => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Controller\ViewController'     => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Controller\PostController'     => __DIR__ . '/src/Market/Controller/PostController.php',
    'Market\Form\CaptchaTrait'             => __DIR__ . '/src/Market/Form/CaptchaTrait.php',
    'Market\Form\CategoryTrait'            => __DIR__ . '/src/Market/Form/CategoryTrait.php',
    'Market\Form\Filter\Float'             => __DIR__ . '/src/Market/Form/Filter/Float.php',
    'Market\Form\ExpireDaysTrait'          => __DIR__ . '/src/Market/Form/ExpireDaysTrait.php',
    'Market\Form\PostForm'                 => __DIR__ . '/src/Market/Form/PostForm.php',
    'Market\Form\PostFormFilter'           => __DIR__ . '/src/Market/Form/PostFormFilter.php',
    'Market\Factory\PostFormFilterFactory' => __DIR__ . '/src/Market/Factory/PostFormFilterFactory.php',
    'Market\Factory\PostControllerFactory' => __DIR__ . '/src/Market/Factory/PostControllerFactory.php',
    'Market\Factory\PostFormFactory'       => __DIR__ . '/src/Market/Factory/PostFormFactory.php',
    'Market\Module'                        => __DIR__ . '/Module.php',
    'MarketTest\SampleTest'                => __DIR__ . '/tests/Market/SampleTest.php',
    'MarketTest\Framework\TestCase'        => __DIR__ . '/tests/Market/Framework/TestCase.php',
);
