<h1>Category: <?php echo $this->escapehtml($this->category); ?></h1>

<?php if($this->listings instanceof Zend\Db\ResultSet\ResultSet) : ?>
<table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid" aria-describedby="dataTables-example_info">
	<thead>
		<tr role="row">
			<th>Item</th>
			<th>Price</th>
			
			<th>Posted</th>
	</thead>
	<tbody>
<?php while($item = $this->listings->current()): ?>
		<tr>
			<td><a href="<?php echo $this->url('market/view/item').$item['listings_id']; ?>"><?php echo $this->escapehtml($item['title']); ?></a></td>
			<td><?php echo $this->escapehtml((float) $item['price']); ?></td>
			
			<td><?php echo $this->escapehtml($item['date_created']); ?></td>
		</tr>
		<?php $this->listings->next(); ?>
<?php endwhile; ?>
	</tbody>
</table>

<?php else: ?>

<?php Zend\Debug\Debug::dump($this->listings); ?>

<?php endif; ?>