<?php if ($this->item) : ?>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><?php echo $this->escapehtml($this->item->title); ?></h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Category</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml(ucwords($this->item->category)); ?>
			</div>
		</div>
	</div>
	<div class="col-lg-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Price</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->price); ?>
			</div>
		</div>
	</div>
	<div class="col-lg-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Date Created</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->date_created); ?>
			</div>
		</div>
	</div>
	<div class="col-lg-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Date Expires</h4>
			</div>
			<div class="panel-body">
				<?php echo ($this->item->date_expires) ? $this->escapehtml($this->item->date_expires) : 'No expires'; ?>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Description</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->description); ?>
			</div>
		</div>
	</div>
</div>
	
<div class="row">
	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Contact Name</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->contact_name); ?>
			</div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Contact Email</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->contact_email); ?>
			</div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Contact Phone</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->contact_phone); ?>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">City</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml(ucwords($this->item->city)); ?>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Country</h4>
			</div>
			<div class="panel-body">
				<?php echo $this->escapehtml($this->item->country); ?>
			</div>
		</div>
	</div>
</div>


	
	<?php if ($this->item->photo_filename): ?>
	<img src="<?php echo $this->basePath($this->item->photo_filename); ?>"  class="img-thumbnail img-responsive">
	<?php else: ?>
	Sem imagem
	<?php endif; ?>
<?php else: ?>
<?php Zend\Debug\Debug::dump($this->item); ?>
<?php endif; ?>
