<?php
$this->headScript()->prependFile($this->basePath('js/meiomask.min.js'), 'text/javascript');
?>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Busca CEP</h1>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">Preencha o CEP para localizar o endeço</div>
			<div class="panel-body">
				<form role="form" id="form_cep">
					<div class="row">
						<div class="col-md-3 col-sm-10">
							<div class="form-group">
								<label>CEP</label> <input class="form-control" id="cep" name="cep">
							</div>
						</div>
						<div class="col-sm-2">
							<div class="form-group">
								<br>
								<button class="btn btn-primary" type="submit" id="enviar">Buscar</button>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 col-sm-12">
							<div class="form-group">
								<label>Endereço</label> <input class="form-control" id="endereco" name="endereco">
							</div>
						</div>
						<div class="col-md-6 col-sm-12">
							<div class="form-group">
								<label>Número</label> <input class="form-control" id="numero" name="numero">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 col-sm-12">
							<div class="form-group">
								<label>Bairro</label> <input class="form-control" id="bairro" name="bairro">
							</div>
						</div>
						<div class="col-md-4 col-sm-12">
							<div class="form-group">
								<label>Cidade</label> <input class="form-control" id="cidade" name="cidade">
							</div>
						</div>
						<div class="col-md-4 col-sm-12">
							<div class="form-group">
								<label>Estado</label> <select class="form-control" id="uf" name="uf">
									<option value="">Selecione</option>
                                    <?php foreach($this->estados as $uf => $nome): ?>
                                    <option value="<?php echo $uf; ?>"><?php echo $nome; ?></option>
                                    <?php endforeach ?>
                                </select>
							</div>
						</div>
					</div>
				</form>
				<div id="alert" class="alert">

                </div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#cep').setMask('cep');
	$('form').submit(function() {
		$('#enviar').text(' Buscando...').prepend('<span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>').attr('disabled', true);

		$.ajax({
		    type: 'post',
		    url: '<?php echo $this->url('correios'); ?>busca',
		    dataType: "json",
		    data: { cep : $('#cep').val() },
		    beforeSend: function() {
		    	$('form *').filter(':input').each(function(){
		    	    $(this).attr('disabled', false);
		    	});
		    	
		    	$('#alert').removeClass('alert-warning alert-success').text();
		    }
		}).done(function(json) {
			$('#alert').addClass('alert-success').text('CEP Encontrado');
			
			$('#endereco').val(json.logradouro).attr('disabled', true);
			$('#bairro').val(json.bairro).attr('disabled', true);
			$('#cidade').val(json.localidade).attr('disabled', true);
			$('#uf').val(json.uf).attr('disabled', true);

			 
		}).fail(function() {
			document.getElementById("form_cep").reset();
		    $('#alert').addClass('alert-warning').text('CEP Não encontrado');
		}).always(function() {
			$('#enviar').text('Buscar').attr('disabled', false);
		});
		
		return false;
	});
});
</script>
